#!/bin/sh

BaseUrl="${BaseUrl:-http://ex-api.localtest.me:5000}"
Html5Mode="${Html5Mode:-false}"
EnableSsl="${EnableSsl:-false}"
EnableAccountCreation="${EnableAccountCreation:-true}"

OAuth="${ConnectionStrings__OAuth:-}"
IFS=';' read -a oauthParts <<< "$OAuth"
for part in ${oauthParts[@]}
do
  key="$( cut -d '=' -f 1 <<< $part )"; echo "key: $key"
  value="$( cut -d '=' -f 2- <<< $part )"; echo "value: $value"

  if [ "$key" == "FacebookId" ]; then
    FacebookAppId=$value
  fi
  if [ "$key" == "GitHubId" ]; then
    GitHubAppId=$value
  fi
  if [ "$key" == "GoogleId" ]; then
    GoogleAppId=$value
  fi
  if [ "$key" == "IntercomId" ]; then
    IntercomAppId=$value
  fi
  if [ "$key" == "MicrosoftId" ]; then
    MicrosoftAppId=$value
  fi
  if [ "$key" == "SlackId" ]; then
    SlackAppId=$value
  fi
done

config="(function () {
  'use strict';

  angular.module('app.config', [])
    .constant('BASE_URL', '$BaseUrl')
    .constant('EXCEPTIONLESS_API_KEY', '$ExceptionlessApiKey')
    .constant('EXCEPTIONLESS_SERVER_URL', '$ExceptionlessServerUrl')
    .constant('FACEBOOK_APPID', '$FacebookAppId')
    .constant('GITHUB_APPID', '$GitHubAppId')
    .constant('GOOGLE_APPID', '$GoogleAppId')
    .constant('INTERCOM_APPID', '$IntercomAppId')
    .constant('LIVE_APPID', '$MicrosoftAppId')
    .constant('SLACK_APPID', '$SlackAppId')
    .constant('STRIPE_PUBLISHABLE_KEY', '$StripePublishableApiKey')
    .constant('SYSTEM_NOTIFICATION_MESSAGE', '$NotificationMessage')
    .constant('USE_HTML5_MODE', $Html5Mode)
    .constant('USE_SSL', $EnableSsl)
    .constant('ENABLE_ACCOUNT_CREATION', $EnableAccountCreation);
}());"

checksum=`echo -n $config | md5sum | cut -c 1-32`
echo $config > "/app/app.config.$checksum.js"
sed -i -E "s/app\.config\..+\.js/app.config.$checksum.js/" /app/index.html

echo "Running NGINX"
nginx
