#!/bin/bash

ApiUrl="${EX_ApiUrl:-http://ex-api.localtest.me:5000}"
EnableAccountCreation="${EX_EnableAccountCreation:-true}"

OAuth="${EX_ConnectionStrings__OAuth:-}"
IFS=';' read -a oauthParts <<< "$OAuth"
for part in ${oauthParts[@]}
do
  key="$( cut -d '=' -f 1 <<< $part )"; echo "key: $key"
  value="$( cut -d '=' -f 2- <<< $part )"; echo "value: $value"

  if [ "$key" == "FacebookId" ]; then
    FacebookAppId=$value
  fi
  if [ "$key" == "GitHubId" ]; then
    GitHubAppId=$value
  fi
  if [ "$key" == "GoogleId" ]; then
    GoogleAppId=$value
  fi
  if [ "$key" == "IntercomId" ]; then
    IntercomAppId=$value
  fi
  if [ "$key" == "MicrosoftId" ]; then
    MicrosoftAppId=$value
  fi
  if [ "$key" == "SlackId" ]; then
    SlackAppId=$value
  fi
done

config="var environment = {
  BASE_URL: '$ApiUrl',
  EXCEPTIONLESS_API_KEY: '$EX_ExceptionlessApiKey',
  EXCEPTIONLESS_SERVER_URL: '$EX_ExceptionlessServerUrl',
  FACEBOOK_APPID: '$FacebookAppId',
  GITHUB_APPID: '$GitHubAppId',
  GOOGLE_APPID: '$GoogleAppId',
  INTERCOM_APPID: '$IntercomAppId',
  LIVE_APPID: '$MicrosoftAppId',
  SLACK_APPID: '$SlackAppId',
  STRIPE_PUBLISHABLE_KEY: '$EX_StripePublishableApiKey',
  SYSTEM_NOTIFICATION_MESSAGE: '$EX_NotificationMessage',
  ENABLE_ACCOUNT_CREATION: $EnableAccountCreation
};";

checksum=`echo -n $config | md5sum | cut -c 1-32`
echo $config > "/app/app.config.$checksum.js"
sed -i -E "s/app\.config\..+\.js/app.config.$checksum.js/" /app/index.html

echo "Running NGINX"
nginx
